### ISSUE TITLE
Neighbouring Text Events are Potentially Split Unnecessarily

### ISSUE THREAD

**Issue by seanaye** [pulldown-cmark/pulldown-cmark#914] opened 2024-06-19 14:40 UTC
I am using pulldown to consume the events via the `into_offset_iter` method and I'm finding that text events can be split up unnecessarily.

Example repro:
```rust
use pulldown_cmark::{Options, Parser};

fn main() {
    let markdown_str = "hello https://google.com/foo_bar_/baz";
    let mut options = Options::empty();
    options.insert(Options::ENABLE_STRIKETHROUGH);

    Parser::new_ext(markdown_str, options)
        .into_offset_iter()
        .for_each(|x| {
            dbg!(x);
        });
}
```

This logs
```
[src/main.rs:12:13] x = (
    Start(
        Paragraph,
    ),
    0..37,
)
[src/main.rs:12:13] x = (
    Text(
        Borrowed(
            "hello https://google.com/foo_bar",
        ),
    ),
    0..32,
)
[src/main.rs:12:13] x = (
    Text(
        Borrowed(
            "_",
        ),
    ),
    32..33,
)
[src/main.rs:12:13] x = (
    Text(
        Borrowed(
            "/baz",
        ),
    ),
    33..37,
)
[src/main.rs:12:13] x = (
    End(
        Paragraph,
    ),
    0..37,
)
```

I would expect this to be a single text event instead of 3.

**Comment by Martin1887** [comment] 2024-06-20 07:51
This is the normal behavior of the pull parser, and a helper function exists to join the events for you: https://docs.rs/pulldown-cmark/latest/pulldown_cmark/utils/struct.TextMergeStream.html.

Duplicate of #906.

**Closed by Martin1887** 2024-06-20 07:51 UTC
