### ISSUE TITLE
Plug-in support

### ISSUE THREAD

**Issue by azerupi** [pulldown-cmark/pulldown-cmark#9] opened 2015-08-11 12:06 UTC
Hi, I have been using pulldown-cmark in my project ([mdBook](https://github.com/azerupi/mdBook)) and it works great! 

One thing I would like to see in the future is some kind of **plug-in API**. In that way you can keep 100% compliance with the Common Mark specs and users would be able to tweak and add features on their own. I have noticed that most of the "issues" are just feature requests that could be mostly resolved by having a plug-in API. 

I know the python markdown module has a plug-in API and if I remember correctly you are able to specify the priority of your plug-in to avoid collisions with built-in "rules".

**Comment by Martin1887** [comment] 2024-03-12 16:31
Closed as duplicate of the more discussed #615.

**Closed by Martin1887** 2024-03-12 16:31 UTC
Labels: long term, extendabilty
