### ISSUE TITLE
Weird HTML parsed result.

### ISSUE THREAD

**Issue by garyhai** [pulldown-cmark/pulldown-cmark#602] opened 2022-07-29 09:19 UTC
The two lines of Commonmark text parsed different results.

Source:
```markdown
<p>Test HTML element</p> Followed by text.

Text before HTML tag <p>HTML Element</p>
```

Result:

```
Html(
    Borrowed(
        "<p>Test HTML element</p> Followed by text.\n",
    ),
)
Some(
    "<p>Test HTML element</p> Followed by text.\n",
)
=*=*=
Start(
    Paragraph,
)
Some(
    "Text before HTML tag <p>HTML Element</p>",
)
Text(
    Borrowed(
        "Text before HTML tag ",
    ),
)
Some(
    "Text before HTML tag ",
)
Html(
    Borrowed(
        "<p>",
    ),
)
Some(
    "<p>",
)
Text(
    Borrowed(
        "HTML Element",
    ),
)
Some(
    "HTML Element",
)
Html(
    Borrowed(
        "</p>",
    ),
)
Some(
    "</p>",
)
=*=*=
End(
    Paragraph,
)
Some(
    "Text before HTML tag <p>HTML Element</p>",
)
```

Is there a solution treat HTML snippet as a inline tag like Strong?

**Comment by Martin1887** [comment] 2023-11-04 11:14
Check if this has been fixed.

**Comment by Martin1887** [comment] 2023-11-04 18:37
I understand that the problem is ` Followed by text.` is parsed out of any paragraph while `HTML Element` is embedded inside a nested paragraph tag.

Not fixed yet.

**Comment by ollpu** [comment] 2024-03-23 07:22
This follows the CommonMark specification and isn't necessarily a bug. An HTML block started by `<p>` is ended by a blank line, not the closing tag.

One way to force the tags to be inline HTML is to add some invisible character before:
```
&ZeroWidthSpace;<p>Test HTML element</p> Followed by text.
```

There's probably a cleaner solution too, depending on the exact use case.

**Closed by ollpu** 2024-03-23 07:22 UTC
Labels: enhancement
